name: MobHeadsV3
version: '${project.version}'
main: io.github.shinyumbreon197.mobheadsv3.MobHeadsV3
api-version: '1.21'
softdepend: [ ProtocolLib ]
authors: [ 197ShinyUmbreon ]
description: All creatures have a chance to drop their head when killed by a Player, and those heads have many effects when worn or placed in the world.
website: https://github.com/197ShinyUmbreon
commands:
  mobheads:
    aliases: mh
    description: Opens a GUI displaying all Vanilla, Player, and Custom heads provided by the plugin.
  summonheaded:
    description: Summons an Entity with a MobHead in their Helmet slot.
    usage: /summonheaded <entityname>
    permission: mh.admin
  mhdebug:
    aliases: mhd
    description: Admin debug only.
    permission: mh.admin
permissions:
  mh.admin:
    description: Server Operator or permissive Admin.
    default: op
  mh.*:
    description: Wildcard permission
    default: op
    children:
      mh.admin: true
